export default {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',

  LOAD_PRODUCT: 'LOAD_PRODUCT',
  LOAD_PRODUCT_ERROR: 'LOAD_PRODUCT_ERROR,',

  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',

  ADD_PRODUCTS_TO_CART: 'ADD_PRODUCTS_TO_CART',
  LOAD_CART_PRODUCT: 'LOAD_CART_PRODUCT',
  DELETE_CART_PRODUCT: 'DELETE_CART_PRODUCT',
  UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',

  ADD_PRODUCTS_TO_FAVORITES: 'ADD_PRODUCTS_TO_FAVORITES',
  DELETE_FAVORITE_PRODUCT: 'DELETE_FAVORITE_PRODUCT',
};
