export default {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',

  LOAD_PRODUCT: 'LOAD_PRODUCT',
  LOAD_PRODUCT_ERROR: 'LOAD_PRODUCT_ERROR,',

  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

  ADD_PRODUCTS_TO_CART: 'ADD_PRODUCTS_TO_CART',
  LOAD_CART_PRODUCT: 'LOAD_CART_PRODUCT',
  DELETE_CART_PRODUCT: 'DELETE_CART_PRODUCT',
  UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',
  UPDATE_PRODUCTS_ERROR: 'UPDATE_PRODUCTS_ERROR',

  ADD_PRODUCTS_TO_FAVORITES: 'ADD_PRODUCTS_TO_FAVORITES',
  DELETE_FAVORITE_PRODUCT: 'DELETE_FAVORITE_PRODUCT',
};
