export default {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',

  LOAD_PRODUCT: 'LOAD_PRODUCT',

  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};
